### ISSUE TITLE
Documentation typo?

### ISSUE THREAD

**Issue by dpsthree** [toolsplus/nx-forge#60] opened 2024-01-23 15:59 UTC
The installation instructions on the readme say to install @toolsplus/nx-nx-forge. Shouldn't it be @toolsplus/nx-forge?

**Comment by dpsthree** [comment] 2024-01-23 16:00
All commands have nx- twice.

**Comment by tbinna** [comment] 2024-01-24 10:21
Thanks @dpsthree, this has been reported before and fixed in the beta branch which is currently pending testing and release.

Duplicate of #52

**Closed by tbinna** 2024-01-24 10:21 UTC
