### ISSUE TITLE
Deploying with a library throws `Error: Bundling failed: Module not found`

### ISSUE THREAD

**Issue by itsjxck** [toolsplus/nx-forge#11] opened 2022-04-28 13:04 UTC
Getting `Error: Bundling failed: Module not found: Error: Can't resolve '@better-harvest/harvest-api' in '/Users/jdadam/nx-better-harvest/dist/apps/better-harvest/src'` when I try to deploy my app after following the guide.

`workspace.json`:
```
{
  "version": 2,
  "projects": {
    "better-harvest": "apps/better-harvest",
    "better-harvest-issue-glance": "apps/better-harvest-issue-glance",
    "harvest-api": "libs/harvest-api"
  }
}
```

`@better-harvest/harvest-api` is imported in `apps/better-harvest/src/index.ts`:
```
import Resolver from "@forge/resolver";
import harvest from "@better-harvest/harvest-api";

const resolver = new Resolver();

resolver.define("harvest.getProjectAssignments", harvest.getProjectAssignments);

export const handler = resolver.getDefinitions();
```

`nx build better-harvest`:
```
nx-better-harvest on  main [✘!?] is 📦 v0.0.0 via ⬢ v16.13.1 
➜ nx build better-harvest

   ✔    2/2 dependent project tasks succeeded [0 read from cache]

   Hint: you can run the command with --verbose to see the full dependent project outputs

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————


> nx run better-harvest:build

Compiling TypeScript files for project "better-harvest"...
Done compiling TypeScript files for project "better-harvest".
Copying better-harvest-issue-glance Custom UI build artifacts...
Done copying better-harvest-issue-glance Custom UI build artifacts.
Patching /Users/jdadam/nx-better-harvest/dist/apps/better-harvest/manifest.yml...
Done patching /Users/jdadam/nx-better-harvest/dist/apps/better-harvest/manifest.yml.
Executor ran for build

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target build for project better-harvest and 2 task(s) it depends on (18s)
```

`nx deploy better-harvest`:
```
nx-better-harvest on  main [✘!?] is 📦 v0.0.0 via ⬢ v16.13.1 took 18s 
➜ nx deploy better-harvest          

> nx run better-harvest:deploy

Running: forge deploy deploy --environment=development
Deploying your app to the development environment.
Press Ctrl+C to cancel.

Running forge lint...
No issues found.

✕ Deploying your app to development...

ℹ Packaging app files

Error: Bundling failed: Module not found: Error: Can't resolve '@better-harvest/harvest-api' in '/Users/jdadam/nx-better-harvest/dist/apps/better-harvest/src'

Rerunning the command with --verbose may give more details.
Exit with error code: 1

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target "better-harvest:deploy" failed

   Failed tasks:
   
   - better-harvest:deploy
   
   Hint: run the command with --verbose for more details.
```

**Comment by tbinna** [comment] 2022-04-29 10:16
Thanks, for highlighting this @itsjxck. I managed to reproduce this. I can see at least two issues with this:

1. I got an error message about flow syntax not being enabled. This seems to be related to [no `.babelrc` file being generated in the library (api) project](https://github.com/nrwl/nx/discussions/8600). I managed to resolve this as suggested in the discussion.
2. The current Forge app TS build retains the import of  '@better-harvest/harvest-api' in the compiled output which cannot be resolved during deployment. This will be a matter of fixing the build to either include the api code as a package or compile it into the app source like the Webpack build for the React app does.

**Comment by tbinna** [comment] 2022-04-29 12:06
I think I have a fix for this. The idea is to use the [Nx Node Webpack executor](https://nx.dev/packages/node/executors/webpack) instead of the plain TS build executor to make sure dependencies get bundled with the app code.
Strangely when testing this with [the sample todo app](https://github.com/toolsplus/forge-todo-app), by analyzing the compiled js file the Forge linter now thinks there are some missing scopes:

```
/.../forge-todo-app/dist/apps/forge-app/src/index.js
831:34  error    Jira endpoint: POST /rest/api/3/permissions/check requires "read:permission:jira" scope  permission-scope-required
```

To me, this looks like a bug in the Forge linter. Deploying with `--no-verify` works.

**Comment by itsjxck** [comment] 2022-04-29 12:46
Interesting. What configuration for the webpack executor worked for you?

**Comment by tbinna** [comment] 2022-05-03 04:12
Currently, the plugin was using the Typescript compilation executor form @nrwl/js. Instead, the PR changes this use the Webpack build from @nrwl/node. You can find the [options passed to the Webpack build in the PR](https://github.com/toolsplus/nx-forge/blob/feature/update-forge-app-build-bundling/packages/forge/src/executors/build/lib/compile-webpack.ts). I will have to investigate a bit more on why the linting fails.

**Closed** 2022-05-05 03:26 UTC
